export type ConceptCategory = "Fact" | "Dimension" | string;

export interface Concept {
  id: string;
  name: string;
  category: ConceptCategory;
}

export interface LevelConfig {
  id: string;
  title: string;
  description: string;
  lessonHtml?: string;
  nextLevelId?: string;
  uiType: "drag_and_drop" | string;
  concepts: Concept[];
  passingThreshold: number; // e.g. 1.0 for 100%
  categories: ConceptCategory[];
}

export const LEVEL_1_CONFIG: LevelConfig = {
  id: "level_1_core",
  title: "Level 1: The Atomic Core",
  description: "Drag the concepts into the correct category: Fact or Dimension.",
  lessonHtml: `
    <div class="prose prose-blue max-w-none mb-6">
      <h3 class="text-xl font-semibold mb-2">Introduction to Dimensional Modeling</h3>
      <p class="mb-4">In a data warehouse, we organize data to make it easy for businesses to answer questions. We do this by breaking the world down into two simple components: <strong>Facts</strong> and <strong>Dimensions</strong>.</p>
      <ul class="list-disc pl-5 mb-4 text-left">
        <li class="mb-2"><strong>Facts</strong> are the measurable, quantitative events that happen in your business (e.g., a sale occurred for $50.00). They are the verbs.</li>
        <li class="mb-2"><strong>Dimensions</strong> are the descriptive, contextual attributes that surround those events (e.g., who bought it, when did they buy it, what store were they in). They are the nouns.</li>
      </ul>
      <p>Mastering this simple distinction is the foundation of all Data Engineering analytics!</p>
    </div>
  `,
  nextLevelId: "level_2_keys",
  uiType: "drag_and_drop",
  passingThreshold: 1.0,
  categories: ["Fact", "Dimension"],
  concepts: [
    { id: "c1", name: "Sales Amount", category: "Fact" },
    { id: "c2", name: "Customer Name", category: "Dimension" },
    { id: "c3", name: "Transaction Date", category: "Dimension" },
    { id: "c4", name: "Discount Applied", category: "Fact" },
    { id: "c5", name: "Store Location", category: "Dimension" }
  ]
};

export const LEVEL_2_CONFIG: LevelConfig = {
  id: "level_2_keys",
  title: "Level 2: The Key Masters",
  description: "Identify which fields act as Surrogate Keys and which are Natural Keys.",
  lessonHtml: `
    <div class="prose prose-purple max-w-none mb-6">
      <h3 class="text-xl font-semibold mb-2">Surrogate Keys vs. Natural Keys</h3>
      <p class="mb-4">To join Facts and Dimensions together efficiently, we use primary keys. But there are two main types of keys in a data warehouse:</p>
      <ul class="list-disc pl-5 mb-4 text-left">
        <li class="mb-2"><strong>Natural Keys</strong> are the real-world identifiers that come from your source systems (like an Employee ID badge number or a Social Security Number).</li>
        <li class="mb-2"><strong>Surrogate Keys</strong> are meaningless, system-generated integers (like 1, 2, 3...) created entirely by the data warehouse to uniquely identify a row, especially when historical tracking is needed.</li>
      </ul>
      <p>Data Engineers always join Fact tables to Dimension tables using Surrogate Keys, never Natural Keys!</p>
    </div>
  `,
  nextLevelId: undefined, // No level 3 yet
  uiType: "drag_and_drop",
  passingThreshold: 1.0,
  categories: ["Natural Key", "Surrogate Key"],
  concepts: [
    { id: "c1", name: "Auto-Incrementing Integer", category: "Surrogate Key" },
    { id: "c2", name: "Vehicle Identification Number (VIN)", category: "Natural Key" },
    { id: "c3", name: "UUID generated by MD5 hash", category: "Surrogate Key" },
    { id: "c4", name: "Customer Email Address", category: "Natural Key" },
    { id: "c5", name: "Source System Product Code", category: "Natural Key" }
  ]
};

export const SYLLABUS_MAP: Record<string, LevelConfig> = {
  [LEVEL_1_CONFIG.id]: LEVEL_1_CONFIG,
  [LEVEL_2_CONFIG.id]: LEVEL_2_CONFIG
};
